In [ ]:
# importing numpy library

import numpy as np

# Declaring array

In [ ]:
a = np.array([1,3,45,6,2],dtype='int16')
a

array([ 1,  3, 45,  6,  2], dtype=int16)

In [ ]:
#two dimensional array
b = np.array([[1,23,4,5,6,6],[4,3,22,44,5,4]])
b

array([[ 1, 23,  4,  5,  6,  6],
       [ 4,  3, 22, 44,  5,  4]])

In [ ]:
#dimension of an array
a.ndim

1

In [ ]:
b.shape

(2, 6)

In [ ]:
b.dtype

dtype('int64')

In [ ]:
a.dtype

dtype('int16')

In [ ]:
a.dtype

dtype('int16')

In [ ]:
#single item size
a.itemsize

2

In [ ]:
b.itemsize

8

In [ ]:
#total size
b.nbytes

96

# Accessign or chanaging specific elements, rows or columns


In [ ]:
print(b)

[[ 1 23  4  5  6  6]
 [ 4  3 22 44  5  4]]


In [ ]:
# get a specific element

print(b[1][3])

44


In [ ]:
# get the last element

print(b[1][-1])

4


In [ ]:
# get a specific row

print(b[0, :])

[ 1 23  4  5  6  6]


In [ ]:
# get a specific column

print(b[:, 2])

[ 4 22]


In [ ]:
# control the step size

print(b[0, 1:6:2])

[23  5  6]


In [ ]:
# change an element

b[0,1] = 33
b

array([[ 1, 33,  4,  5,  6,  6],
       [ 4,  3, 22, 44,  5,  4]])

# Different types of Arrays

In [ ]:
# zero matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
# all 1 matrix

np.ones((4,4), dtype='int8')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [ ]:
# using any number

np.full((3,3), 88)

array([[88, 88, 88],
       [88, 88, 88],
       [88, 88, 88]])

In [ ]:
# copy the shape of another matrix/array

np.full_like(a, 10)

array([10, 10, 10, 10, 10], dtype=int16)

In [ ]:
# array of random numbers

np.random.rand(3,3)

array([[0.6651037 , 0.24531705, 0.13124723],
       [0.81892776, 0.30869859, 0.1070101 ],
       [0.86001097, 0.54812802, 0.20911423]])

In [ ]:
np.random.random_sample(a.shape)

array([0.95211947, 0.10467259, 0.80947217, 0.315889  , 0.77877889])

In [ ]:
# array of random numbers with selected data type

np.random.randint(10, high=15 ,size=(3,3)) # high is optional

array([[10, 12, 14],
       [14, 10, 12],
       [12, 12, 12]])

In [ ]:
np.random.randint(-2,5, size=(3,3))

array([[ 2,  0,  2],
       [ 1,  4,  0],
       [-2,  4,  4]])

In [ ]:
# indentity matrix

np.identity(5, dtype='int8')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [ ]:
# repeat values

arr = np.array([1,2,4])
r1 = np.repeat(arr, 3)
r1

array([1, 1, 1, 2, 2, 2, 4, 4, 4])

In [ ]:
arr = np.array([[1,2,4]])
r1 = np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 4],
       [1, 2, 4],
       [1, 2, 4]])

In [ ]:
one = np.ones((5,5), dtype='int8')
print(one)
zero = np.zeros((3,3), dtype='int8')

print(zero)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
zero[1][1] = 9
zero

array([[0, 0, 0],
       [0, 9, 0],
       [0, 0, 0]], dtype=int8)

In [ ]:
one[1:4, 1:4] = zero
print(one)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
# be carefull while copying arrays

m = np.array([1,2,3])
n = m
print(n)

[1 2 3]


In [ ]:
n[0] = 100
print(m)

[100   2   3]


In [ ]:
 # solution

s = np.array([3,4,5])
p = s.copy()
p[0] = 66

print(s)

[3 4 5]
