In [ ]:
import numpy as np

# Declaring array

In [ ]:
a = np.array([1,3,45,6,2],dtype='int16')
a

array([ 1,  3, 45,  6,  2], dtype=int16)

In [ ]:
#two dimensional array
b = np.array([[1,23,4,5,6,6],[4,3,22,44,5,4]])
b

array([[ 1, 23,  4,  5,  6,  6],
       [ 4,  3, 22, 44,  5,  4]])

In [ ]:
#dimension of an array
a.ndim

1

In [ ]:
b.shape

(2, 6)

In [ ]:
b.dtype

dtype('int64')

In [ ]:
a.dtype

dtype('int16')

In [ ]:
a.dtype

dtype('int16')

In [ ]:
#single item size
a.itemsize

2

In [ ]:
b.itemsize

8

In [ ]:
#total size
b.nbytes

96

# Accessign or chanaging specific elements, rows or columns


In [ ]:
print(b)

[[ 1 23  4  5  6  6]
 [ 4  3 22 44  5  4]]


In [ ]:
# get a specific element

print(b[1][3])

44


In [ ]:
# get the last element

print(b[1][-1])

4


In [ ]:
# get a specific row

print(b[0, :])

[ 1 23  4  5  6  6]


In [ ]:
# get a specific column

print(b[:, 2])

[ 4 22]


In [ ]:
# control the step size

print(b[0, 1:6:2])

[23  5  6]


In [ ]:
# change an element

b[0,1] = 33
b

array([[ 1, 33,  4,  5,  6,  6],
       [ 4,  3, 22, 44,  5,  4]])

# Different types of Arrays

In [ ]:
# zero matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
# all 1 matrix

np.ones((4,4), dtype='int8')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [ ]:
# using any number

np.full((3,3), 88)

array([[88, 88, 88],
       [88, 88, 88],
       [88, 88, 88]])

In [ ]:
# copy the shape of another matrix/array

np.full_like(a, 10)

array([10, 10, 10, 10, 10], dtype=int16)

In [ ]:
# array of random numbers

np.random.rand(3,3)

array([[0.2347585 , 0.49106985, 0.39694222],
       [0.68157994, 0.86601654, 0.20852975],
       [0.73500322, 0.63536971, 0.75444577]])

In [ ]:
np.random.random_sample(a.shape)

array([0.87975524, 0.8420866 , 0.8364842 , 0.87917363, 0.38173087])

In [ ]:
# array of random numbers with selected data type

np.random.randint(10, high=15 ,size=(3,3)) # high is optional

array([[14, 12, 10],
       [13, 13, 10],
       [12, 11, 11]])

In [ ]:
np.random.randint(-2,5, size=(3,3))

array([[-2, -2,  1],
       [ 4,  2,  1],
       [-1,  2,  4]])

In [ ]:
# indentity matrix

np.identity(5, dtype='int8')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [ ]:
# repeat values

arr = np.array([1,2,4])
r1 = np.repeat(arr, 3)
r1

array([1, 1, 1, 2, 2, 2, 4, 4, 4])

In [ ]:
arr = np.array([[1,2,4]])
r1 = np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 4],
       [1, 2, 4],
       [1, 2, 4]])

In [ ]:
one = np.ones((5,5), dtype='int8')
print(one)
zero = np.zeros((3,3), dtype='int8')

print(zero)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
zero[1][1] = 9
zero

array([[0, 0, 0],
       [0, 9, 0],
       [0, 0, 0]], dtype=int8)

In [ ]:
one[1:4, 1:4] = zero
print(one)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
# be carefull while copying arrays

m = np.array([1,2,3])
n = m
print(n)

[1 2 3]


In [ ]:
n[0] = 100
print(m)

[100   2   3]


In [ ]:
 # solution

s = np.array([3,4,5])
p = s.copy()
p[0] = 66

print(s)

[3 4 5]


# Mathematics

In [ ]:
q = np.array([1,2,4,5])
print(q)

[1 2 4 5]


In [ ]:
q + 2

array([3, 4, 6, 7])

In [ ]:
q - 2

array([-1,  0,  2,  3])

In [ ]:
q * 2

array([ 2,  4,  8, 10])

In [ ]:
q / 2

array([0.5, 1. , 2. , 2.5])

In [ ]:
# power

q ** 2

array([ 1,  4, 16, 25])

In [ ]:
np.sin(q)

array([ 0.84147098,  0.90929743, -0.7568025 , -0.95892427])

In [ ]:
np.cos(0)

np.float64(1.0)

# Linear Algebra

In [ ]:
d = np.ones((3,3))
d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
f = np.full((3,2),2)
f

array([[2, 2],
       [2, 2],
       [2, 2]])

In [ ]:
np.matmul(d,f)

array([[6., 6.],
       [6., 6.],
       [6., 6.]])

In [ ]:
# find the determinant

np.linalg.det(d)


np.float64(0.0)

# Statistics

In [ ]:
print(b)

[[ 1 33  4  5  6  6]
 [ 4  3 22 44  5  4]]


In [ ]:
np.min(b, axis = 1)

array([1, 3])

In [ ]:
np.max(b, axis=1)

array([33, 44])

In [ ]:
np.mean(b)

np.float64(11.416666666666666)

In [ ]:
np.median(b, axis=1)

array([5.5, 4.5])

In [ ]:
np.sum(b)

np.int64(137)

# Reorganizing Arrays

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(before.shape)

(2, 4)


In [ ]:
after = before.reshape(4,2)
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# vertically stacking vectors
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])

np.vstack([a1,a2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.vstack([a1,a2,a1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [ ]:
# horizontal stacking

b1 = np.ones((2,4))
b2 = np.zeros((2,2))

np.hstack([b1,b2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

In [ ]:
# load data from file

filedata = np.genfromtxt('data.txt', delimiter=',')

print(filedata)

[nan nan nan]
